@extends('layouts.sidebar')
@extends('layouts.app')
@section('maincontent')
    <ol class="breadcrumb fs-4 fw-bold">
        <li class="breadcrumb-item">Billing</li>
        <li class="breadcrumb-item active text-info">Invoice Index</li>
    </ol>

    <div style="width: 500px" class="row form-container shadow-sm">
        <form action="" method="GET">
            @csrf
            <div class="row">
                <div class="col form-group">
                    <label class="col-form-label col-form-label-sm mt-4" for="inputSmall">From Date</label>
                    <input class="form-control form-control-sm" type="date" name="fromDate" id="inputSmall" required
                        value="<?php echo date('Y-m-01'); ?>">
                </div>

                <div class="col form-group">
                    <label class="col-form-label col-form-label-sm mt-4" for="inputSmall">To Date</label>
                    <input class="form-control form-control-sm" type="date" id="inputSmall" name="toDate" required
                        value="<?php echo date('Y-m-30'); ?>">
                </div>

                <div class="col form-group">
                    <label class="col-form-label col-form-label-sm mt-4" for="inputSmall">Invoice For</label>
                    <select class="form-control form-select-sm" id="inputSmall" name="invFor" required>
                        <option value="" disabled selected hidden>--select invoice for--</option>
                        @foreach ($invFor as $row)
                            <option value="{{ $row->id }}">{{ $row->invoice_for }}</option>
                        @endforeach
                    </select>
                </div>

                <br>
                {{-- <div> --}}
                <button class="btn btn-info save-btn" style="margin-left: 10px">show invoices</button>
                {{-- </div> --}}
            </div>
        </form>
    </div>
    <br>
    <br> <br>
    <h3 class="shadow">
        All Invoice List
    </h3>

    <table class="table table-striped shadow-sm table-sm">
        <thead>
            <tr class="bg-gradient text-white fw-normal" style="background-color: #131d36">
                <th scope="col" style="text-align: center">Batch no.</th>
                <th scope="col" style="text-align: center">Inv for</th>
                <th scope="col" style="text-align: center">Inv type</th>
                <th scope="col" style="text-align: center">Inv month year</th>
                <th scope="col" style="text-align: center">Inv date</th>
                <th scope="col" style="text-align: center">Generated by</th>
                <th scope="col" style="text-align: center">Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach ($showInvoice as $key => $data)
                <tr>
                    <td>{{ $data->batch_number }}</td>
                    <td>
                        @if ($data->invoice_for == 1)
                            Coloasia
                        @elseif ($data->invoice_for == 2)
                            MCloud
                        @elseif ($data->invoice_for == 3)
                            Bogra POI
                        @elseif ($data->invoice_for == 4)
                            Sylhet POI
                        @elseif ($data->invoice_for == 5)
                            SMS
                        @endif
                    </td>
                    <td>
                        @if ($data->invoice_type == 1)
                            Pre-paid
                        @elseif ($data->invoice_type == 2)
                            Post-paid
                        @endif
                    </td>
                    <td>{{ $data->invoice_month_year }}</td>
                    <td>{{ $data->invoice_date }}</td>
                    <td>{{ $data->invoice_generated_by }}</td>

                    <td>
                        <a class="btn btn-info" data-toggle="tooltip" data-placement="left" title="Download" href="{{ url('pdf-invoice/' . $data->batch_number) }}" target="_blank"><img
                                class="my-icon" src="images/download.png" alt=""></a>

                        <a class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="View Batch" href="{{ url('batch-invoice-details/' . $data->batch_number) }}"><img
                                class="my-icon" src="images/view.png" alt=""></a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
